name: shorten-url-backend

services:
  database:
    container_name: shorten-url-database
    image: postgres:alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - path: ./.env
        required: true
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - '${DB_PORT}:5432'
    restart: always

  url-shortener-service:
    container_name: url-shortener-service
    build:
      context: .
      dockerfile: services/url-shortener-service/Dockerfile
      target: development
    environment:
      - PORT=80
    env_file:
      - path: ./.env
        required: true
    ports:
      - ${SHORTENER_PORT}:80
    volumes:
      - ./services/url-shortener-service:/app
      - /app/node_modules
    depends_on:
      - database
    restart: always

  iam-service:
    container_name: iam-service
    build:
      context: .
      dockerfile: services/iam-service/Dockerfile
      target: development
    environment:
      - PORT=80
    env_file:
      - path: ./.env
        required: true
    ports:
      - ${IAM_PORT}:80
    volumes:
      - ./services/iam-service:/app
      - /app/node_modules
    depends_on:
      - database

volumes:
  pg-data:
